version: "3.9"

services:
  authservice:
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    container_name: authservice
    ports:
      - "5081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - SigningCert__Base64=${SigningCert__Base64}
      - SigningCert__Password=${SigningCert__Password}
      - EncryptCert__Base64=${EncryptCert__Base64}
      - EncryptCert__Password=${EncryptCert__Password}
      - Cors__AllowedOrigins=${Cors__AllowedOrigins}
      - Swagger__AllowedUsernames=${Swagger__AllowedUsernames}
      - Ldap__TechnicalUsername=${Ldap__TechnicalUsername}
      - Ldap__TechnicalDomain=${Ldap__TechnicalDomain}
      - Ldap__TechnicalPassword=${Ldap__TechnicalPassword}
      - Ldap__AllowedEmeaOfficeNames=${Ldap__AllowedEmeaOfficeNames}
      - AzureAd__TenantId=${AzureAd__TenantId}
      - AzureAd__ClientId=${AzureAd__ClientId}
      - AzureAd__Issuer=${AzureAd__Issuer}
    depends_on:
      - authpostgres

  authpostgres:
    image: postgres:18.1
    container_name: authpostgres
    ports:
      - 5082:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - authpostgresdata:/var/lib/postgresql

  authpgadmin:
    image: dpage/pgadmin4
    container_name: authpgadmin
    restart: "unless-stopped"
    ports:
      - 5083:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - authpgadmindata:/var/lib/pgadmin
    depends_on:
      - authpostgres

volumes:
  authpostgresdata:
  authpgadmindata:
