version: "3.9"

services:
  authservice:
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    container_name: authservice
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
    depends_on:
      - postgres
    ports:
      - "5081:8080"

  postgres:
    image: postgres:18.1
    container_name: authdb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - authdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: authpgadmin
    restart: "unless-stopped"
    ports:
      - 5083:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - authpgadmindata:/var/lib/pgadmin

volumes:
  authdata:
  authpgadmindata:
